### ISSUE TITLE
The dot won't disappear on monterey :(

### ISSUE THREAD

**Issue by katerlouis** [FuzzyIdeas/YellowDot#1]
macOS 12.0.1 on latest 16'' M1 Pro Max Macbook.

Funny side note: When I wanted to make a screenshot as proof, the dot smoothly animated away :D
But I guess that is a macOS thing, isnt it?

And yes: I have allowed "Bedienungshilfen" :(

![image](https://user-images.githubusercontent.com/1983382/148039343-6380de96-992f-41c4-8230-46a370f56c25.png)

![image](https://user-images.githubusercontent.com/1983382/148039289-63f1aa05-7abb-471c-9551-66144063329e.png)

**Comment by alin23** [comment]
In case your confusion is about the Control Center icon dot:

YellowDot only hides the corner dot as exemplified here:

![image](https://user-images.githubusercontent.com/3819725/148093515-2aa757ad-f06c-4633-956b-f5ce0c81623d.png)

The Control Panel icon dot can't be hidden as it's embedded inside the icon.

<img width="42" alt="image" src="https://user-images.githubusercontent.com/3819725/148093631-4b0c4f57-6f3d-40be-ba65-037fb3373916.png">

Hiding the corner dot is what's most needed because that dot doesn't go away when the menubar is not visible.

**Comment by katerlouis** [comment]
Oh, okay– thanks for clearing that up!

I now know it's off-topic, but you don't happen to know a way to change the icon in this state? 😅

**Comment by alin23** [comment]
There's no way to do that unfortunately. The icon lives in `/System/Library/CoreServices/ControlCenter.app/Contents/Resources/Assets.car` which is a read-only path when System Integrity Protection is enabled.

If you're really determined to do that, you could disable SIP, extract Assets.car using something like [cartool](https://github.com/steventroughtonsmith/cartool), change the icon containing the dot, then reassemble `Assets.car` using something like the system `assetutil`.
