### ISSUE TITLE
macOS 12.2 changed how the dot is rendered

### ISSUE THREAD

**Issue by DaveFlashNL** [FuzzyIdeas/YellowDot#4]
the dot won't hide anymore

**Comment by alin23** [comment]
Thanks for reporting!

It would be great if you could contribute with a PR. I can't install betas for the next few months.

**Comment by cormiertyshawn895** [comment]
The recording indicator is no longer a window within the Control Center process. Therefore YellowDot can’t move or hide it with Accessibility APIs.

Hiding the microphone recording indicator light requires a new approach, so I made [Recording Indicator Utility](https://github.com/cormiertyshawn895/RecordingIndicatorUtility) which supports macOS 12.2, letting you turn off the recording indicator light across all apps.

[![Screen recording of Recording Indicator Utility](https://github.com/cormiertyshawn895/RecordingIndicatorUtility/raw/master/RecordingIndicatorUtility/Screenshots/screenshot-animation.gif)](https://github.com/cormiertyshawn895/RecordingIndicatorUtility)

You can also choose to hide the recording indicator of your favorite apps or in full-screen apps.

[![Screenshot of Recording Indicator Utility](https://github.com/cormiertyshawn895/RecordingIndicatorUtility/raw/master/RecordingIndicatorUtility/Screenshots/screenshot-per-app-settings.jpg)](https://github.com/cormiertyshawn895/RecordingIndicatorUtility)

**Comment by alin23** [comment]
Whoa, clever solution: https://github.com/cormiertyshawn895/RecordingIndicatorUtility/blob/ae07739a6853345db094c7836d454dfee752e10a/RecordingIndicatorInjection/NSObject%2BRecordingIndicatorInjection.m#L68-L98

Too bad it requires SIP disabled.

You know,  it's ironic that so much fuss was made around this dot and so many Apple news sites published about it because people wanted a way to disable it, and what did Apple do? Make it even harder to remove the dot.

@cormiertyshawn895 so how does the dot look in 12.2 on fullscreen apps?

**Comment by cormiertyshawn895** [comment]
> Whoa, clever solution: https://github.com/cormiertyshawn895/RecordingIndicatorUtility/blob/ae07739a6853345db094c7836d454dfee752e10a/RecordingIndicatorInjection/NSObject%2BRecordingIndicatorInjection.m#L68-L98

Thanks for the shout-out! Trying to make do with what we have.

> @cormiertyshawn895 so how does the dot look in 12.2 on fullscreen apps?

It looks the same as before.
